"""Refactor RolePermission to use composite PK and inherit from Base

Revision ID: 5f9ec48b034c
Revises: 572270043c96
Create Date: 2025-06-25 20:52:10.156814

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f9ec48b034c'
down_revision = '572270043c96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_master_data_name_per_category', 'master_data', ['category', 'name'])
    op.drop_column('master_data', 'is_active')
    op.drop_column('master_data', 'properties')
    op.drop_column('role_permissions', 'id')
    op.drop_column('role_permissions', 'created_at')
    op.drop_column('role_permissions', 'updated_at')
    op.add_column('transactions', sa.Column('entity_type_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'transactions', 'master_data', ['entity_type_id'], ['id'])
    op.drop_column('transactions', 'entity_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'entity_type_id')
    op.add_column('role_permissions', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('role_permissions', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('role_permissions', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('master_data', sa.Column('properties', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('master_data', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint('unique_master_data_name_per_category', 'master_data', type_='unique')
    # ### end Alembic commands ###
