"""Add is_active and created_by_user_id to Role

Revision ID: d089cf90aa2f
Revises: 5f9ec48b034c
Create Date: 2025-06-27 17:37:03.998578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd089cf90aa2f'
down_revision = '5f9ec48b034c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permissions', 'module_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('roles', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('roles', sa.Column('created_by_user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'roles', 'users', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_column('roles', 'created_by_user_id')
    op.drop_column('roles', 'is_active')
    op.alter_column('permissions', 'module_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
